server:
  port: 7070
spring:
  application:
    name: ms-order
  datasource:
    url: jdbc:postgresql://localhost:5432/order_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        format_sql: true
  liquibase:
    enabled: true
    change-log: classpath:/liquibase/changelog-master.yml
    default-schema: public
    drop-first: false
  cache:
    type: redis
  data:
    redis:
      host: localhost
      port: 6379
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    publisher-confirm-type: correlated
    listener:
      simple:
        acknowledge-mode: manual
        retry:
          enabled: true
          max-attempts: 3              # 1 initial try + 2 retries
          initial-interval: 1000       # 1 second before first retry
          multiplier: 2.0              # Exponential backoff factor
          max-interval: 5000           # Maximum 5 seconds between retries

rabbit:
  queue:
    order:
      q: ORDER_Q
      dlq: ORDER_DLQ